# Default SpiderJS configuration

# Target URL (required)
url: ""

# Timeout for requests
timeout: 30s

# Maximum crawl depth
max_depth: 3

# User agent
user_agent: "SpiderJS/1.0.0"

# Number of concurrent requests
concurrent: 10

# Output file path
output: ""

# Output format (console, json, html, xml)
format: "console"

# Log level (debug, info, warn, error)
log_level: "info"

# Log file path
log_file: ""

# Disable colored output
no_color: false

# Proxy URL
proxy: ""

# Skip TLS certificate verification
skip_tls_verify: false

# Scanner options
scan_options:
  # Include XSS scanning
  include_xss: true
  
  # Include injection scanning
  include_injection: true
  
  # Include CSRF scanning
  include_csrf: true
  
  # Include CORS scanning
  include_cors: true
  
  # Include security headers scanning
  include_headers: true
  
  # Include cookie security scanning
  include_cookies: true
  
  # Include supply chain scanning
  include_supply_chain: true
  
  # Include prototype pollution scanning
  include_prototype: true
  
  # Include subdomains in scan
  include_subdomains: false
  
  # Perform active scanning (potentially intrusive)
  active_scan: false
  
  # Fuzzing level (0-3)
  fuzz_level: 1 